num_genes: 15000
num_snps: 1000
num_nullsnps: 0
sample_size: 800
allele_freq: 0.5
num_targets: [60, 80, 100, 150, 200, 300, 400, 600, 1000, 2000]
identity: True
iterations: 100
beta_sd: fixed
beta_value: [0.1]
rep: 100
sig_threshold: 0.05
