num_genes: 15000
num_snps: 800
num_nullsnps: 0
sample_size: 100
allele_freq: 0.5
num_targets: [400, 600, 800, 1000, 1250, 1500, 1750, 2000]
identity: True
iterations: 100
beta_sd: fixed
beta_value: [0]
rep: 100
sig_threshold: 0.05
